package com.example.medicalsymptomprescreener.di

import android.content.Context
import androidx.room.Room
import com.example.medicalsymptomprescreener.BuildConfig
import com.example.medicalsymptomprescreener.data.api.GeminiRetrofitService
import com.example.medicalsymptomprescreener.data.api.GeminiTriageApi
import com.example.medicalsymptomprescreener.data.api.GeminiTriageApiImpl
import com.example.medicalsymptomprescreener.data.api.GooglePlacesApiImpl
import com.example.medicalsymptomprescreener.data.api.GooglePlacesRetrofitService
import com.example.medicalsymptomprescreener.data.local.SymptomDao
import com.example.medicalsymptomprescreener.data.local.SymptomDatabase
import com.example.medicalsymptomprescreener.data.monitor.ConnectivityNetworkMonitor
import com.example.medicalsymptomprescreener.data.repository.FacilityRepositoryImpl
import com.example.medicalsymptomprescreener.data.repository.SymptomRepositoryImpl
import com.example.medicalsymptomprescreener.data.repository.TranslationRepositoryImpl
import com.example.medicalsymptomprescreener.domain.monitor.NetworkMonitor
import com.example.medicalsymptomprescreener.domain.repository.FacilityRepository
import com.example.medicalsymptomprescreener.domain.repository.SymptomRepository
import com.example.medicalsymptomprescreener.domain.repository.TranslationRepository
import com.example.medicalsymptomprescreener.data.api.AppCheckInterceptor
import com.google.android.gms.tasks.Tasks
import com.google.firebase.appcheck.FirebaseAppCheck
import com.google.gson.Gson
import com.google.gson.GsonBuilder
import dagger.Binds
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import java.util.concurrent.TimeUnit
import javax.inject.Named
import javax.inject.Singleton

/**
 * Hilt module providing all application-scoped singleton dependencies.
 *
 * Two separate [Retrofit] instances are created and distinguished with [@Named]:
 * - `"gemini"` → `generativelanguage.googleapis.com` (Gemini 2.5 Flash)
 * - `"places"` → `places.googleapis.com` (Google Places API v1)
 *
 * API keys are read from [BuildConfig] fields generated by the Secrets Gradle Plugin.
 * The plugin strips dots and lowercases keys: `gemini.api.key` → `geminiapikey`,
 * `maps.api.key` → `mapsapikey`.
 *
 * Interface bindings (NetworkMonitor, SymptomRepository, FacilityRepository) are in
 * the companion [BindingsModule] which uses `@Binds` for zero-overhead injection.
 *
 * S: Single Responsibility — provides singleton infrastructure dependencies via Hilt.
 */
@Module
@InstallIn(SingletonComponent::class)
object AppModule {

    /** Provides a shared [Gson] instance for JSON serialization across both API clients. */
    @Provides
    @Singleton
    fun provideGson(): Gson = GsonBuilder().create()

    /**
     * Provides a shared [OkHttpClient] with logging.
     * Logs full request/response bodies in DEBUG builds. Silent in release builds
     * to avoid leaking symptom data to logcat.
     */
    @Provides
    @Singleton
    fun provideOkHttpClient(): OkHttpClient =
        OkHttpClient.Builder()
            .addInterceptor(
                HttpLoggingInterceptor().apply {
                    level = if (BuildConfig.DEBUG) HttpLoggingInterceptor.Level.BODY
                    else HttpLoggingInterceptor.Level.NONE
                }
            )
            .build()

    /**
     * Provides the [AppCheckInterceptor] to dynamically retrieve and inject Firebase App Check tokens.
     * Uses a lambda-based token provider and task awaiting for graceful degradation and full testability.
     */
    @Provides
    @Singleton
    fun provideAppCheckInterceptor(): AppCheckInterceptor =
        AppCheckInterceptor {
            try {
                val appCheck = FirebaseAppCheck.getInstance()
                val task = appCheck.getAppCheckToken(false)
                val appCheckToken = Tasks.await(task, 5, TimeUnit.SECONDS)
                appCheckToken.token
            } catch (e: Exception) {
                // Invariant: No android.util.Log in data/ or domain/ layers.
                System.err.println("Firebase App Check token fetch failed: ${e.message}")
                null
            }
        }

    /**
     * Provides a specialized [OkHttpClient] specifically for the Gemini Retrofit client,
     * including the [AppCheckInterceptor] for cryptographic attestation.
     */
    @Provides
    @Singleton
    @Named("gemini")
    fun provideGeminiOkHttpClient(
        appCheckInterceptor: AppCheckInterceptor
    ): OkHttpClient =
        OkHttpClient.Builder()
            .addInterceptor(appCheckInterceptor)
            .addInterceptor(
                HttpLoggingInterceptor().apply {
                    level = if (BuildConfig.DEBUG) HttpLoggingInterceptor.Level.BODY
                    else HttpLoggingInterceptor.Level.NONE
                }
            )
            .build()

    /**
     * Provides the Gemini [Retrofit] instance pointed at `generativelanguage.googleapis.com`.
     * Distinguished from the Places instance via [@Named("gemini")].
     */
    @Provides
    @Singleton
    @Named("gemini")
    fun provideGeminiRetrofit(@Named("gemini") okHttpClient: OkHttpClient, gson: Gson): Retrofit =
        Retrofit.Builder()
            .baseUrl("https://generativelanguage.googleapis.com/")
            .client(okHttpClient)
            .addConverterFactory(GsonConverterFactory.create(gson))
            .build()

    /** Provides the [GeminiRetrofitService] interface backed by the Gemini [Retrofit] instance. */
    @Provides
    @Singleton
    fun provideGeminiRetrofitService(@Named("gemini") retrofit: Retrofit): GeminiRetrofitService =
        retrofit.create(GeminiRetrofitService::class.java)

    /**
     * Provides the [GeminiTriageApi] implementation with the API key from [BuildConfig].
     *
     * `BuildConfig.geminiapikey` — the Secrets Gradle Plugin lowercases and strips dots
     * from `gemini.api.key`. In CI, this resolves to "PLACEHOLDER" from `local.defaults.properties`.
     */
    @Provides
    @Singleton
    fun provideGeminiTriageApi(
        service: GeminiRetrofitService,
        gson: Gson
    ): GeminiTriageApi = GeminiTriageApiImpl(service, BuildConfig.geminiapikey, gson)

    /**
     * Provides the Google Places [Retrofit] instance pointed at `places.googleapis.com`.
     * Distinguished from the Gemini instance via [@Named("places")].
     */
    @Provides
    @Singleton
    @Named("places")
    fun providePlacesRetrofit(okHttpClient: OkHttpClient, gson: Gson): Retrofit =
        Retrofit.Builder()
            .baseUrl("https://places.googleapis.com/")
            .client(okHttpClient)
            .addConverterFactory(GsonConverterFactory.create(gson))
            .build()

    /** Provides the [GooglePlacesRetrofitService] interface backed by the Places [Retrofit] instance. */
    @Provides
    @Singleton
    fun provideGooglePlacesRetrofitService(@Named("places") retrofit: Retrofit): GooglePlacesRetrofitService =
        retrofit.create(GooglePlacesRetrofitService::class.java)

    /**
     * Provides [GooglePlacesApiImpl] with the Maps/Places API key from [BuildConfig].
     *
     * `BuildConfig.mapsapikey` — the Secrets Gradle Plugin strips dots and lowercases
     * `maps.api.key`. In CI, this resolves to "PLACEHOLDER" from `local.defaults.properties`.
     */
    @Provides
    @Singleton
    fun provideGooglePlacesApiImpl(service: GooglePlacesRetrofitService): GooglePlacesApiImpl =
        GooglePlacesApiImpl(service, BuildConfig.mapsapikey)

    /**
     * Provides the Room database instance.
     * `fallbackToDestructiveMigration()` clears data on schema change — acceptable for
     * a portfolio app; production apps would provide explicit migrations.
     */
    @Provides
    @Singleton
    fun provideSymptomDatabase(@ApplicationContext context: Context): SymptomDatabase =
        Room.databaseBuilder(context, SymptomDatabase::class.java, "symptom_history.db")
            .fallbackToDestructiveMigration()
            .build()

    /** Provides the [SymptomDao] from the [SymptomDatabase]. */
    @Provides
    @Singleton
    fun provideSymptomDao(database: SymptomDatabase): SymptomDao = database.symptomDao()
}

/**
 * Hilt `@Binds` module for interface-to-implementation wiring.
 *
 * `@Binds` generates no wrapper code at runtime — the injection graph resolves
 * directly to the implementation class, unlike `@Provides` which creates a factory method.
 *
 * S: Single Responsibility — binds domain interfaces to their data-layer implementations.
 * D: Dependency Inversion — ensures all injection sites depend on abstractions.
 */
@Module
@InstallIn(SingletonComponent::class)
abstract class BindingsModule {

    /** Binds [ConnectivityNetworkMonitor] as the [NetworkMonitor] implementation. */
    @Binds
    @Singleton
    abstract fun bindNetworkMonitor(impl: ConnectivityNetworkMonitor): NetworkMonitor

    /** Binds [SymptomRepositoryImpl] as the [SymptomRepository] implementation. */
    @Binds
    @Singleton
    abstract fun bindSymptomRepository(impl: SymptomRepositoryImpl): SymptomRepository

    /** Binds [FacilityRepositoryImpl] as the [FacilityRepository] implementation. */
    @Binds
    @Singleton
    abstract fun bindFacilityRepository(impl: FacilityRepositoryImpl): FacilityRepository

    /**
     * Binds [TranslationRepositoryImpl] as the [TranslationRepository] implementation.
     *
     * Scoped as a [Singleton] so a single ML Kit [Translator] instance is shared across
     * all ViewModels — avoids redundant model loads and native resource allocation.
     */
    @Binds
    @Singleton
    abstract fun bindTranslationRepository(impl: TranslationRepositoryImpl): TranslationRepository
}
